---
abstract: 'Perl redis shell'
author:
  - 'David Leadbeater <dgl@dgl.cx>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-redisp
requires:
  Data::Dump: 0
  Eval::WithLexicals: 1.002
  Moo: 0
  Tie::Redis: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-redisp
  repository: git://github.com/dgl/App-redisp
version: 0.13
